---
name: 'test'

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  go-test:
    name: go-test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: go get .
      - name: Run go test
        run: go test -v ./...
