---
name: 'test'

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  go-test:
    name: go-test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        go-version: ['1.22.0']
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: go get .
      - name: Run go test
        run: go test -v ./...
